milvus:
  address: "localhost:19530"
  username: ""
  password: ""
  dbname: "test"

ali:
  apikey: "sk-737281fd1c884de7a57601f41c310e81"
  baseurl:  "https://dashscope.aliyuncs.com/compatible-mode/v1"

